name: desktop-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "desktop/**"
      - "ui/**"
      - "docs/windows-desktop.md"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend deps
        working-directory: ui
        run: npm install

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        working-directory: desktop
        run: npm install

      - name: Build Windows MSI
        working-directory: desktop
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pymes-suite-msi
          path: desktop/src-tauri/target/release/bundle/msi/*.msi
