name: pymerp_app
publish_to: 'none'
description: Cliente Flutter para PYMERP (Web/Windows/Android)
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  geolocator: ^9.0.2
  geolocator_web: ^2.2.0

  # Opcional para web
  universal_html: ^2.2.4
  flutter_pdfview: ^1.4.0
  web_socket_channel: ^2.4.0
  uuid: ^4.5.1
  printing: ^5.13.4
  file_saver: ^0.2.12
  path_provider: ^2.1.5
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0

flutter:
  uses-material-design: true
