ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS address VARCHAR(200),
  ADD COLUMN IF NOT EXISTS commune VARCHAR(120),
  ADD COLUMN IF NOT EXISTS business_activity VARCHAR(120),
  ADD COLUMN IF NOT EXISTS phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS email VARCHAR(120);
